-- +----------+--------------+------+-----+---------+----------------+
-- | Field    | Type         | Null | Key | Default | Extra          |
-- +----------+--------------+------+-----+---------+----------------+
-- | id       | int          | NO   | PRI | NULL    | auto_increment |
-- | username | varchar(100) | YES  |     | NULL    |                |
-- | email    | varchar(200) | YES  |     | NULL    |                |
-- | verified | tinyint      | YES  |     | NULL    |                |
-- | token    | varchar(100) | YES  |     | NULL    |                |
-- | password | varchar(255) | YES  |     | NULL    |                |
-- +----------+--------------+------+-----+---------+----------------+
